### PR TITLE
Documentation of the bootstrap process

### PR DESCRIPTION
**Pull request by rptb1**
I've written up the notes from our conversation today into a maintainable document.

I suggest cross-referencing it from the source code. At Ravenbrook we use tags -- see for example the string “design.mps.splay.prop” in https://github.com/Ravenbrook/mps/blob/master/code/splay.c . These kinds of cross references have survived 20 years of change and several source control systems!

This is an update to #230 with corrected branching!

### CODE REVIEW

**Comment by rptb1** [comment]
@drmeister How does SBCL fit into the bootstrap process?

**Comment by Shinmera** [comment]
SBCL runs the scraper parts.

**Comment by rptb1** [comment]
@Shinmera Thanks for https://github.com/drmeister/clasp/issues/182 .  I'll get an overview direct from @drmeister and include details from that, and insert a reference to it.  Do you know of any other docs (in issues etc.) that can be usefully referenced from bootstrap.rst ?

**Comment by Shinmera** [comment]
I don't think so. Outside of the work done to clean up things such as in the makefiles, the bootstrap process has not been approached by anyone.

**Comment by drmeister** [comment]
I've held off merging this pull request because I rewrote the build system using 'waf' and some things have changed although the document is largely correct.

Should I merge this and edit the file or edit the file somehow before merging?

**Comment by Shinmera** [comment]
As long as you don't merge it into testing directly as it is here I don't really care. The changes seem rather minimal.

**Comment by Shinmera** [comment]
Merged as #304

**Pull request closed without merging**
