### PR TITLE
s/ecl-min/clasp-min/

### PR DESCRIPTION
**Pull request by dkochmanski**
This PR replaces all `ecl-min` references with appropriate feature conditions with `clasp-min` (improving compatibility of ECL and Clasp codebases)

### CODE REVIEW

**Comment by dkochmanski** [comment]
This needs to be tested if builds right (I don't have Clasp working build yet) – I believe I got things right though

**Comment by dkochmanski** [comment]
Seems to work. Built successfully with the new feature, compiled quicklisp and swank without problems:
```
> *modules*

("SWANK-PRESENTATIONS" "SWANK-REPL" "SWANK-C-P-C" "SWANK-UTIL" "ASDF" "asdf"
 "UIOP" "uiop" "SB-BSD-SOCKETS" "SOCKETS")
> *features*

(:SWANK :QUICKLISP :ASDF-PACKAGE-SYSTEM :ASDF3.1 :ASDF3 :ASDF2 :ASDF :FORMATTER
 :CLASP-BOOT :CLOS :CCLASP :INTERACTIVE :USE-EXPENSIVE-BACKTRACE :USE-BOEHMDC
 :RELEASE-BUILD :VARARGS :LLVM39 :LLVM38 :X86-64 :LINUX :OS-UNIX :UNIX :CLASP
 :SILENCE-CCLASP-COMPILE-WARNINGS :TARGET-OS-LINUX :ADDRESS-MODEL-64)
>
```
I believe it's ready to be merged

**Comment by drmeister** [comment]
This is a merge request into  drmeister:dev from dkochmanski:dev-ecl.

Is there a way to merge into drmeister:dev-ecl from dkochmanski:dev-ecl ?

That way I could build it in drmeister:dev-ecl and check things out before I merge it into drmeister:dev

That's the right thing to do isn't it?

Alternatively, I can create a 'dev-temp' branch and leave that in reserve, merge this into 'dev' and if everything is ok delete 'dev-temp' and proceed in 'dev'.   If there is an unexpected catastrophe I have 'dev-temp' in reserve?   Or I guess I can unwind the changes in 'dev' somehow.  But they will be on github.

Advice would be very much appreciated.

**Comment by drmeister** [comment]
No problem - stassats pointed me to the "command line instructions" button above - sweet!

**Comment by Shinmera** [comment]
Closing since this is contained in #290

**Pull request closed without merging**
